### ISSUE TITLE
Training on 700 X 1100 results in error for train_512p.sh

### ISSUE THREAD

**Issue by PraveerSINGH** [NVIDIA/pix2pixHD#10]
Hey,

I am training a pix2pixHD model on images of size 700 X 1100.
However it results into concatenation error.  Can it be trained for 700 X 1100 images ?
For the moment, I have adapted to train on sizes of 512 X 512 crops.
I am also wandering if the code supports validation on only square images (or fixed 1024 X 2048 size images) or does it also support any variable rectangular size images ?
Thanks in advance.

**Comment by tcwang0509** [comment]
If you crop the image into 512x512, there shouldn't be any concatenation errors. Usually the concatenation error is caused by the downsamplings and upsamplings in the network, when the image size is not divisible by 2. Does it show on which line the error happens?
Validation shouldn't be a problem, as long as the image size is divisible by some power of 2 (depending on how many downsamplings you use).

**Comment by fabio-C** [comment]
Hi @tcwang0509 I am trying to train my own 512x512 dataset. I am not using label or instance map. I am putting my train images in **_train_A_** and **_train_B_** directory. Could you please tell me if this commands is correct?
`python train.py --name mydataset --resize_or_crop none --loadSize 512 --fineSize 512 --label_nc 0 --no_instance`
Thank you very much.
