### ISSUE TITLE
Perceptual Loss Issues

### ISSUE THREAD

**Issue by iRmantou** [NVIDIA/pix2pixHD#18]
Hi: @mingyuliutw @junyanz 
I have read your paper carefully, I noticed you use a perceptual loss in paper with hyperparameters λ=10, weights = 1/Mi and Mi is the number of elements of i-th layer in VGG19,  however, I checked the codes you released where the weight of loss is  [1.0/32, 1.0/16, 1.0/8, 1.0/4, 1.0], I am confused with these numbers 32, 16... What's the elements you're referring to?

**Comment by tcwang0509** [comment]
It is because the image size becomes smaller as we go up the layers, so I normalized it. I actually experienced not normalizing it and the results were pretty similar.

**Comment by iRmantou** [comment]
Thank you, I understand it now :)

**Comment by Justin-Tan** [comment]
So to clarify, the weights [1.0/32, 1.0/16, 1.0/8, 1.0/4, 1.0] refer to the number of elements in the ith layer of the VGG network, normalized by the image size? 

and do you have a similar situation for the feature matching loss? There you have defined the weights as 
```
feat_weights = 4.0 / (self.opt.n_layers_D + 1)
D_weights = 1.0 / self.opt.num_D
```
could this be replaced by taking the mean of the absolute difference instead of using the L1 loss with the given weights?
